### ISSUE TITLE
compatibility with [SOTA] FBOCC

### ISSUE THREAD

**Issue by billbliss3** [OpenGVLab/DCNv4#19]
As we known:

     FBOCC is a awesome project for both OCC and 3DDet.

     Recently, I just change the InternImage image backbone in the FBOCC to FlashInternImage instead.

     But by the same project baseline and with same param and env, the FlashInternImage run with wierd ERROR as follows.

     I guess the Resnet ERROR is caused by the bev_backbone, which is not compatible with image backbone FlashInternImage.
     I am not sure. 

    
      Traceback (most recent call last):
      File "tools/train.py", line 372, in <module>
        main()
      File "tools/train.py", line 361, in main
        train_model(
      File "/data/Project/fbocc/mmdet3d/apis/train.py", line 352, in train_model
        train_detector(
      File "/data/Project/fbocc/mmdet3d/apis/train.py", line 327, in train_detector
        runner.run(data_loaders, cfg.workflow)
      File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 138, in run
        iter_runner(iter_loaders[i], **kwargs)
      File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 68, in train
        self.call_hook('after_train_iter')
      File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
        getattr(hook, fn_name)(self)
      File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/hooks/optimizer.py", line 272, in after_train_iter
        self.loss_scaler.scale(runner.outputs['loss']).backward()
      File "/opt/conda/lib/python3.8/site-packages/torch/_tensor.py", line 307, in backward
        torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
      File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 154, in backward
        Variable._execution_engine.run_backward(
      File "/opt/conda/lib/python3.8/site-packages/torch/autograd/function.py", line 199, in apply
        return user_fn(self, *args)
      File "/opt/conda/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 122, in backward
        outputs = ctx.run_function(*detached_inputs)
      File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
        return forward_call(*input, **kwargs)
      File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
        input = module(input)
      File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
        return forward_call(*input, **kwargs)
      File "/opt/conda/lib/python3.8/site-packages/mmdet/models/backbones/resnet.py", line 90, in forward
        out = _inner_forward(x)
      File "/opt/conda/lib/python3.8/site-packages/mmdet/models/backbones/resnet.py", line 73, in _inner_forward
        out = self.conv1(x)
      File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
        return forward_call(*input, **kwargs)
      File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 446, in forward
        return self._conv_forward(input, self.weight, self.bias)
      File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
        return F.conv2d(input, weight, bias, self.stride,  
    RuntimeError: set_sizes_and_strides is not allowed on a Tensor created from .data or .detach().
    If your intent is to change the metadata of a Tensor (such as sizes / strides / storage / storage_offset)
    without autograd tracking the change, remove the .data / .detach() call and wrap the change in a `with torch.no_grad():` block.
    For example, change:
        x.data.set_(y)
    to:
        with torch.no_grad():
            x.set_(y)
    ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 11671) of binary: /opt/conda/bin/python
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
        main()
      File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
        launch(args)
      File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
        run(args)
      File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
        elastic_launch(
      File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
        return launch_agent(self._config, self._entrypoint, list(args))
      File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
        raise ChildFailedError(
    torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
    ============================================================
    tools/train.py FAILED
    ------------------------------------------------------------
    Failures:
      <NO_OTHER_FAILURES>
    ------------------------------------------------------------
    Root Cause (first observed failure):
    [0]:
      time      : 2024-01-24_01:52:41
      host      : localhost.vm
      rank      : 0 (local_rank: 0)
      exitcode  : 1 (pid: 11671)
      error_file: <N/A>
      traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
    ============================================================

**Comment by zhiqi-li** [comment]
Did you use FlashInternImage as Bev-backbone rather than image-backbone?

**Comment by billbliss3** [comment]
> Did you use FlashInternImage as Bev-backbone rather than image-backbone?

李博 您好：

我之前使用的InternImage作为ImageBackbone。顺利运行。在相同的环境和参数情况下，改用了FlashInternImage作ImageBackbone.但是遇到了上面的报错。提到了ResNet。
我猜测是不是和BevBackbone的ResNet有什么地方不兼容。我也不确定。

**Comment by billbliss3** [comment]
@zhiqi-li 
I just turn the bevbackbone and header to None, and still have the same problem.
It seems not caused by bevbackbone.

Why the error log has resnet?
