### ISSUE TITLE
module 'DCNv4' has no attribute 'DCNv4'

### ISSUE THREAD

**Issue by 1104358653** [OpenGVLab/DCNv4#2]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/opt/conda/lib/python3.8/site-packages/mmseg/models/segmentors/encoder_decoder.py", line 36, in __init__
    self.backbone = builder.build_backbone(backbone)
  File "/opt/conda/lib/python3.8/site-packages/mmseg/models/builder.py", line 20, in build_backbone
    return BACKBONES.build(cfg)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 215, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AttributeError: FlashInternImage: module 'DCNv4' has no attribute 'DCNv4'

**Comment by collabzhk** [comment]
I met a similiar problem,  as I ran the train program, the error occurred:
    core_op=getattr(DCNv4, core_op),
AttributeError: module 'DCNv4' has no attribute 'DCNv4'
then I check the attributes through print(dir(DCNv4)) and it returns ：
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
May I have an answer? Really appreciate it!

**Comment by shiomi326** [comment]
I have the same issue.

**Comment by sym330** [comment]
i can not find the module ext

**Comment by YuwenXiong** [comment]
Hi, thanks for raising this up, and sorry for the inconvenience. Now this issue has been fixed with the `1.0.0.post2` release

**Comment by P1ng3609** [comment]
> Hi, thanks for raising this up, and sorry for the inconvenience. Now this issue has been fixed with the `1.0.0.post2` release

您好，我也有相同的问题。
Traceback (most recent call last):
  File "train_embedding.py", line 161, in <module>
    train(opt)
  File "train_embedding.py", line 74, in train
    net = DB_Embedding_Model()
  File "/home/xueyunpei/try/VideoTextSCM-main/db_model/model_v3.py", line 184, in __init__
    self.db = SegDetectorModel()
  File "/home/xueyunpei/try/VideoTextSCM-main/db_model/model_v3.py", line 174, in __init__
    self.model = BasicModel()
  File "/home/xueyunpei/try/VideoTextSCM-main/db_model/model_v3.py", line 165, in __init__
    self.backbone = deformable_resnet50()
  File "/home/xueyunpei/try/VideoTextSCM-main/db_model/resnet.py", line 408, in deformable_resnet50
    model = ResNet(Bottleneck, [3, 4, 6, 3],
  File "/home/xueyunpei/try/VideoTextSCM-main/db_model/resnet.py", line 296, in __init__
    self.layer2 = self._make_layer(
  File "/home/xueyunpei/try/VideoTextSCM-main/db_model/resnet.py", line 330, in _make_layer
    layers.append(block(self.inplanes, planes,
  File "/home/xueyunpei/try/VideoTextSCM-main/db_model/resnet.py", line 232, in __init__
    from assets.ops.dcn import DCNv4
  File "/home/xueyunpei/try/VideoTextSCM-main/assets/ops/dcn/DCNv4/__init__.py", line 1, in <module>
    from .functions import DCNv4Function, FlashDeformAttnFunction
  File "/home/xueyunpei/try/VideoTextSCM-main/assets/ops/dcn/DCNv4/functions/__init__.py", line 10, in <module>
    from .flash_deform_attn_func import FlashDeformAttnFunction
  File "/home/xueyunpei/try/VideoTextSCM-main/assets/ops/dcn/DCNv4/functions/flash_deform_attn_func.py", line 19, in <module>
    from DCNv4 import ext
ModuleNotFoundError: No module named 'DCNv4'
请问如何解决？

**Comment by Wulingtian** [comment]
> I met a similiar problem, as I ran the train program, the error occurred: core_op=getattr(DCNv4, core_op), AttributeError: module 'DCNv4' has no attribute 'DCNv4' then I check the attributes through print(dir(DCNv4)) and it returns ： ['**doc**', '**file**', '**loader**', '**name**', '**package**', '**path**', '**spec**'] May I have an answer? Really appreciate it!

已解决
