### ISSUE TITLE
Error in running demo file using DCNV4

### ISSUE THREAD

**Issue by githigher** [OpenGVLab/DCNv4#39]
Thank you very much for your contribution!
When I run the following code：

```
import DCNv4
help(DCNv4)
```

The following error message has occurred：

```
Traceback (most recent call last):
  File "mytest.py", line 10, in <module>
    import DCNv4
  File "/home/coop/anaconda3/envs/v2xvit/lib/python3.7/site-packages/DCNv4/__init__.py", line 1, in <module>
    from .functions import DCNv4Function, FlashDeformAttnFunction
  File "/home/coop/anaconda3/envs/v2xvit/lib/python3.7/site-packages/DCNv4/functions/__init__.py", line 10, in <module>
    from .flash_deform_attn_func import FlashDeformAttnFunction
  File "/home/coop/anaconda3/envs/v2xvit/lib/python3.7/site-packages/DCNv4/functions/flash_deform_attn_func.py", line 34, in <module>
    raise NotImplementedError
NotImplementedError
free(): invalid pointer
Aborted (core dumped)
```

I tried downloading or running make. sh compilation and installation of DCNv4 using pip, but it still hasn't been resolved.

**Comment by kepurG** [comment]
Call me wechat number 13862010554，windows and linux are ok，we have a group can discuss model together
