### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Dratlan** [OpenGVLab/DCNv4#74]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/nas-data/code/gan_research-dev/DCNv4/DCNv4_op/DCNv4/__init__.py", line 1, in <module>
    from .functions import DCNv4Function, FlashDeformAttnFunction
  File "/workspace/nas-data/code/gan_research-dev/DCNv4/DCNv4_op/DCNv4/functions/__init__.py", line 10, in <module>
    from .flash_deform_attn_func import FlashDeformAttnFunction
  File "/workspace/nas-data/code/gan_research-dev/DCNv4/DCNv4_op/DCNv4/functions/flash_deform_attn_func.py", line 19, in <module>
    from DCNv4 import ext
ImportError: cannot import name 'ext' from partially initialized module 'DCNv4' (most likely due to a circular import) (/workspace/nas-data/code/gan_research-dev/DCNv4/DCNv4_op/DCNv4/__init__.py)
how to solve a circular import in this code?

**Comment by ZhangQianZhe** [comment]
I meet the same queHello, I encountered the same error as you, I checked the code file, and did not find the ext file, May I ask you to find a solutionstion,do you
