### ISSUE TITLE
ImportError: cannot import name 'ext' from 'DCNv4

### ISSUE THREAD

**Issue by hahahh-dev** [OpenGVLab/DCNv4#81]
Traceback (most recent call last):
  File "C:\Users\yxp\Desktop\dtueval\GoMVS-main\test1.py", line 3, in <module>
    from DCNv4.DCNv4_op.DCNv4.modules.dcnv4 import DCNv4
  File "C:\Users\yxp\Desktop\dtueval\GoMVS-main\DCNv4\DCNv4_op\DCNv4\__init__.py", line 1, in <module>
    from .functions import DCNv4Function, FlashDeformAttnFunction
  File "C:\Users\yxp\Desktop\dtueval\GoMVS-main\DCNv4\DCNv4_op\DCNv4\functions\__init__.py", line 10, in <module>
    from .flash_deform_attn_func import FlashDeformAttnFunction
  File "C:\Users\yxp\Desktop\dtueval\GoMVS-main\DCNv4\DCNv4_op\DCNv4\functions\flash_deform_attn_func.py", line 19, in <module>
    from DCNv4 import ext
ImportError: cannot import name 'ext' from 'DCNv4' (C:\Users\yxp\Desktop\dtueval\GoMVS-main\DCNv4\__init__.py)

**Comment by 2805651606** [comment]
> 回溯（最近一次调用最后一次）： 文件“C:\Users\yxp\Desktop\dtueval\GoMVS-main\test1.py”，第 3 行，来自 DCNv4.DCNv4_op.DCNv4.modules.dcnv4 导入 DCNv4 文件“C:\Users\yxp\Desktop\dtueval\GoMVS-main\DCNv4\DCNv4_op\DCNv4_ _init_ _.py”，第 1 行，来自 .functions 导入 DCNv4Function、FlashDeformAttnFunction 文件“C:\Users\yxp\Desktop\dtueval\GoMVS-main\DCNv4\DCNv4_op\DCNv4\functions_ _init_ _.py”，第 10 行，来自 .flash_deform_attn_func 导入 FlashDeformAttnFunction 文件“C:\Users\yxp\Desktop\dtueval\GoMVS-main\DCNv4\DCNv4_op\DCNv4\functions\flash_deform_attn_func.py”，第 19 行，来自 DCNv4 导入 ext ImportError：无法从‘DCNv4’导入名称‘ext’（C:\Users\yxp\Desktop\dtueval\GoMVS-main\DCNv4_ _init_ _.py）

你好，请问你解决这个问题了？

**Comment by bye111** [comment]
同样的疑惑

**Comment by Xiang-M-J** [comment]
可能是python程序所在的目录有DCNv4这个文件夹，换个目录试试看
