### ISSUE TITLE
CNv4-1.0.0.post2-py3.10-linux-x86_64.egg/DCNv4/ext.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv

### ISSUE THREAD

**Issue by yellowaug** [OpenGVLab/DCNv4#94]
Error content
----------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 5, in <module>
    from ultralytics.cfg import entrypoint
  File "/home/yoloproject/ultralytics/__init__.py", line 11, in <module>
    from ultralytics.models import NAS, RTDETR, SAM, YOLO, FastSAM, YOLOWorld
  File "/home/yoloproject/ultralytics/models/__init__.py", line 3, in <module>
    from .fastsam import FastSAM
  File "/home/yoloproject/ultralytics/models/fastsam/__init__.py", line 3, in <module>
    from .model import FastSAM
  File "/home/yoloproject/ultralytics/models/fastsam/model.py", line 5, in <module>
    from ultralytics.engine.model import Model
  File "/home/yoloproject/ultralytics/engine/model.py", line 12, in <module>
    from ultralytics.engine.results import Results
  File "/home/yoloproject/ultralytics/engine/results.py", line 15, in <module>
    from ultralytics.data.augment import LetterBox
  File "/home/yoloproject/ultralytics/data/__init__.py", line 3, in <module>
    from .base import BaseDataset
  File "/home/yoloproject/ultralytics/data/base.py", line 17, in <module>
    from ultralytics.data.utils import FORMATS_HELP_MSG, HELP_URL, IMG_FORMATS
  File "/home/yoloproject/ultralytics/data/utils.py", line 18, in <module>
    from ultralytics.nn.autobackend import check_class_names
  File "/home/yoloproject/ultralytics/nn/__init__.py", line 3, in <module>
    from .tasks import (
  File "/home/yoloproject/ultralytics/nn/tasks.py", line 13, in <module>
    from ultralytics.nn.modules import (
  File "/home/yoloproject/ultralytics/nn/modules/__init__.py", line 89, in <module>
    from .DCNV4 import *
  File "/home/yoloproject/ultralytics/nn/modules/DCNV4.py", line 4, in <module>
    from DCNv4.modules.dcnv4 import DCNv4
  File "/usr/local/lib/python3.10/dist-packages/DCNv4-1.0.0.post2-py3.10-linux-x86_64.egg/DCNv4/__init__.py", line 1, in <module>
    from .functions import DCNv4Function, FlashDeformAttnFunction
  File "/usr/local/lib/python3.10/dist-packages/DCNv4-1.0.0.post2-py3.10-linux-x86_64.egg/DCNv4/functions/__init__.py", line 10, in <module>
    from .flash_deform_attn_func import FlashDeformAttnFunction
  File "/usr/local/lib/python3.10/dist-packages/DCNv4-1.0.0.post2-py3.10-linux-x86_64.egg/DCNv4/functions/flash_deform_attn_func.py", line 19, in <module>
    from DCNv4 import ext
ImportError: /usr/local/lib/python3.10/dist-packages/DCNv4-1.0.0.post2-py3.10-linux-x86_64.egg/DCNv4/ext.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv
--------------------------------------------------------------------------------------------------
python version 3.10.2
cuda 12.1 
torch 2.5.1
torchvision  0.20.1
老哥，这个问题能解决吗？
hey bro this issus be resolved?
感谢~
thk very very~

**Comment by Narrowunknown** [comment]
Same problem, anyone solved yet?
